name-template: Micronaut OpenAPI $NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    label: "type: enhancement"
  - title: 🐛 Bug Fixes
    label: "type: bug"
  - title: 🛠 Dependency upgrades
    label: "type: dependency-upgrade"
  - title: ❌ Breaking Changes
    label: "type: breaking"    
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
