By default Micronaut will automatically at compile time build out the Swagger YAML definition from your defined controllers and methods. For example given the following class:

.Hello World Example
snippet::io.micronaut.configuration.openapi.docs.controllers.HelloController[tags="imports,clazz", project-base="docs-examples/example]

The resulting output will be:

.Example Generated Swagger Output
[source,yaml]
----
paths:
  /hello/{name}:
    get:
      description: ""
      operationId: hello
      parameters:
      - name: name
        in: path
        description: The person's name
        required: true
        explode: false
        schema:
          type: string
      responses:
        default:
          description: The greeting
          content:
            text/plain:
              schema:
                type: string
----

Notice how the javadoc comments are used to fill out the description of the API. If this is not desirable then you can take full control by augmenting your definition with Swagger annotations:

.Using Swagger Annotations
snippet::io.micronaut.configuration.openapi.docs.controllers.annotations.HelloController[tags="imports,clazz", project-base="docs-examples/example]