You also can generate file in Asciidoc format. Then you can convert Asciidoc to another format: `Markdown`, `HTML`, `PDF` or `DOCX`.

To enable generation file in adoc format just set property `-Dmicronaut.openapi.adoc.enabled=true` and add micronaut-openapi-adoc dependency to classpath:

[source,groovy]
----
annotationProcessor("io.micronaut.openapi:micronaut-openapi-adoc")
----

Adoc generator based on Apache Freemarker templates, and you can override full template or just customize part of them.

.Available options
[%header,caption=,cols=".^10a,.^14a,.^10a"]
|===
|`micronaut.openapi.adoc.enabled` | System property that enables or disables open api asciidoc conversion. | Default: `true`
|`micronaut.openapi.adoc.template.dir` | Template directory path. | Default: `classpath:/template`
|`micronaut.openapi.adoc.template.filename` | Main template filename. | Default: `openApiDoc.ftl` (in classpath)
|`micronaut.openapi.adoc.output.dir` | Output directory path. | Default: standard micronaut openapi output directory path
|`micronaut.openapi.adoc.output.filename` | Final `adoc` file name. | Default: the same as openapi spec. filename
|`micronaut.openapi.adoc.templates.*` | Prefix for custom template names. You can override any of the templates that are used in the default implementation to change only part of the resulting document. |
|===

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-openapi-adoc.html[Generate API Documentation in AsciiDoc with the generated OpenAPI specification of your Micronaut application.] to learn more.
