You can set custom classes to create different open api schemas for selected classes:

[configuration]
----
micronaut:
  openapi:
    schema:
      org.somepackage.MyComplexType: java.lang.String
      org.somepackage.MyComplexType2: java.lang.Integer
----

or by system properties:

[source,commandline]
----
-Dmicronaut.openapi.schema.org.somepackage.MyComplexType=java.lang.String -Dmicronaut.openapi.schema.org.somepackage.MyComplexType2=java.lang.Integer
----

or by openapi.properties

[source,properties]
----
micronaut.openapi.schema.org.somepackage.MyComplexType=java.lang.String
micronaut.openapi.schema.org.somepackage.MyComplexType2=java.lang.Integer
----

Also, it can be used for replace classes schema with generics, for example, if you use jaxb generated classes and have custom serializer for JAXBElement class.
And you can set custom schemas for different type args.
For example if you have this classes structure:

snippet::io.micronaut.configuration.openapi.docs.customserializers.MyDto,io.micronaut.configuration.openapi.docs.customserializers.XmlElement,io.micronaut.configuration.openapi.docs.customserializers.XmlElement2,io.micronaut.configuration.openapi.docs.customserializers.XmlElement3[tags="clazz", project-base="docs-examples/example", source="main"]

You can customize classes structure for openapi schema:

snippet::io.micronaut.configuration.openapi.docs.customserializers.MyJaxbElement,io.micronaut.configuration.openapi.docs.customserializers.MyJaxbElement2,io.micronaut.configuration.openapi.docs.customserializers.MyJaxbElement3[tags="clazz", project-base="docs-examples/example", source="main"]

And set openapi properties to map classes to custom openapi schema classes:

[configuration]
----
micronaut:
  openapi:
    schema:
      jakarta.xml.bind.JAXBElement: io.micronaut.configuration.openapi.docs.customserializers.MyJaxbElement
      jakarta.xml.bind.JAXBElement<io.micronaut.configuration.openapi.docs.customserializers.XmlElement2>: io.micronaut.configuration.openapi.docs.customserializers.MyJaxbElement2
      jakarta.xml.bind.JAXBElement<io.micronaut.configuration.openapi.docs.customserializers.XmlElement3>: io.micronaut.configuration.openapi.docs.customserializers.MyJaxbElement3
----

[IMPORTANT]
====
After changing these settings, a complete recompilation of the project is necessary to ensure that the new settings are applied correctly.
====
