To get started add Micronaut's `openapi` to the annotation processor scope of your build configuration:

dependency:micronaut-openapi[scope="annotationProcessor", groupId="io.micronaut.openapi"]

NOTE: For Kotlin, add the `micronaut-openapi` dependency in https://docs.micronaut.io/4.4.3/guide/#kaptOrKsp[kapt or ksp scope], and for Groovy add `micronaut-openapi` in compileOnly scope.

To use the https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations[Swagger Annotations] or Micronaut OpenAPI annotations add them to compile classpath

dependency:micronaut-openapi-annotations[scope="compileOnly", groupId="io.micronaut.openapi"]

NOTE: Also, do not forget that for the correct operation of the annotation processor, the correct parameter
names in the controllers are required, therefore it is recommended that all libraries from which you plan
to add controllers be compiled with the `-parameters` flag. For example like this (with gradle build):
[source,groovy]
----
tasks.withType(JavaCompile).configureEach {
    options.compilerArgs = [
            '-parameters'
    ]
}
----
