Micronaut can generate views for your generated OpenApi specification. Currently https://github.com/swagger-api/swagger-ui[Swagger-ui], https://github.com/Rebilly/ReDoc[Redoc] and https://github.com/mrin9/RapiDoc[RapiDoc] are supported.
You can also use https://mrin9.github.io/RapiPdf/[RapiPdf] to generate a PDF from your spec file.

The resources needed to render the views (javascript, css, ...) are loaded from CDNs: https://unpkg.com[unpkg.com] and https://fonts.googleapis.com/[fonts.googleapis.com].

By default the generation of views is disabled. To turn it on you have to set the following system property `micronaut.openapi.views.spec`.
The string syntax is a series of comma-separated key-value pairs, to enable and configure the views. 

.System Property
[source]
----
micronaut.openapi.views.spec=redoc.enabled=true,rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop
----

For instance in Gradle for Kotlin projects:

.Gradle
[source,shell]
----
JAVA_TOOL_OPTIONS=-Dmicronaut.openapi.views.spec=redoc.enabled=true,rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop \
        ./gradlew --no-daemon clean assemble
----

or in Gradle for Java projects:

.Gradle
[source,groovy]
----
tasks.withType(JavaCompile) {
    options.fork = true
    options.forkOptions.jvmArgs << '-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop'

    ...
}
----

or in Maven:

.Maven
[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
                <fork>true</fork>
                <compilerArgs>
                    <arg>-J-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop</arg>
                    ...
                </compilerArgs>
            </configuration>
        </plugin>
    </plugins>
</build>
----

or in Maven with Groovy:

.Maven + Groovy
[source,xml]
----
<build>
    <plugins>
        <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>properties-maven-plugin</artifactId>
        <version>1.0.0</version>
        <executions>
          <execution>
            <goals>
              <goal>set-system-properties</goal>
            </goals>
            <configuration>
              <properties>
                <property>
                  <name>micronaut.openapi.views.spec</name>
                  <value>rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop</value>
                </property>
              </properties>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
</build>
----

The views will be generated to the `META-INF/swagger/views/[swagger-ui | redoc | rapidoc]` directory of your project’s class output.

The following properties are supported:

 * `mapping.path=[string]`: The path from where the swagger specification will be served by the http server. Default is `swagger`.
 * `redoc.enabled=[true | false]`: When 'true' the Redoc view is generated.
 * `rapidoc.enabled=[true | false]`: When 'true' the RapiDoc view is generated.
 * `swagger-ui.enabled=[true | false]`: When 'true' the Swagger-ui view is generated.
 * `redoc.version=[string]`: The version of Redoc to use. Default is to use the latest available.
 * `redoc.[expand-default-server-variables, menu-toggle, only-required-in-samples, payload-sample-idx, sort-props-alphabetically, untrusted-spec, expand-responses, show-extensions, native-scrollbars, path-in-middle-panel, suppress-warnings, hide-hostname, disable-search, json-sample-expand-level, scroll-y-offset, hide-download-button, no-auto-auth, theme, hide-single-request-sample-tab, required-props-first, hide-loading]`. See https://github.com/Redocly/redoc#redoc-options-object[Redoc Options] for a description.
 * `rapidoc.version=[string]`: The version of RapiDoc to use. Default is to use the latest available.
 * `rapidoc.[style, schema-style, nav-accent-color, show-header, schema-expand-level, response-area-height, allow-authentication, default-api-server, match-paths, allow-server-selection, api-key-name, nav-hover-bg-color, goto-path, theme, text-color, bg-color, api-key-value, header-color, primary-color, sort-tags, nav-bg-color, render-style, heading-text, allow-try, layout, sort-endpoints-by, allow-spec-url-load, nav-text-color, nav-hover-text-color, show-info, regular-font, allow-spec-file-load, server-url, schema-description-expanded, allow-search, api-key-location, mono-font, default-schema-tab]`. See https://mrin9.github.io/RapiDoc/api.html[RapiDoc Options] for a description.
 * `swagger-ui.version=[string]`: The version of Swagger-ui to use. Default is to use the latest available.
 * `swagger-ui.[displayOperationId, oauth2RedirectUrl, showMutatedRequest, deepLinking, supportedSubmitMethods, defaultModelsExpandDepth, layout, defaultModelRendering, docExpansion, filter, validatorUrl, showCommonExtensions, maxDisplayedTags, withCredentials, displayRequestDuration, showExtensions]`. See https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/configuration.md[Swagger UI Configuration] for a description.
 * `swagger-ui.theme=[DEFAULT | MATERIAL | FEELING_BLUE | FLATTOP | MONOKAI | MUTED | NEWSPAPER | OUTLINE]`: The theme of swagger-ui to use. These are case insensitive. Default is `DEFAULT`. See https://github.com/ostranme/swagger-ui-themes[Swagger UI Themes].
 
Views also supports RapiPdf, to enable it use `rapipdf.enabled=true`.
It will add a button to the view to generate a PDF from the spec file.

RapiPdf supports the following options:

 * `rapipdf.[include-api-details, pdf-title, include-api-list, include-security, input-bg, hide-input, pdf-footer-text, button-bg, pdf-primary-color, pdf-schema-style, button-label, pdf-alternate-color, include-info, include-toc, button-color, style, input-color]`. See https://mrin9.github.io/RapiPdf/[RapiPdf Attributes] for a description.

To expose the views, you also must expose the generated `yaml`:

.Exposing Swagger YAML And Views
[source,yaml]
----
micronaut:
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            redoc:
                paths: classpath:META-INF/swagger/views/redoc
                mapping: /redoc/**
            rapidoc:
                paths: classpath:META-INF/swagger/views/rapidoc
                mapping: /rapidoc/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**
----

With the above configuration in place when you run your application you can access your Swagger documentation at +http://localhost:8080/[redoc|rapidoc|swagger-ui]+.
By default the views expect to find the `yaml` under `/swagger`, if you change this mapping to something else:

.Exposing Swagger YAML
[source,yaml]
----
micronaut:
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swaggerYAML/**
....
----
You will need to set the `mapping.path` property accordingly: `micronaut.openapi.views.spec=mapping.path=swaggerYAML...`.

== Server Context Path

In micronaut configuration file you can define a server context path (with `micronaut.server.context-path`) which serves as a base path for all routes.
Since the yaml specification file and the views are generated at compile time, these resources are not aware of this runtime setting.

It is still possible for the views to work in case a context path is defined:
* Use a `HttpServerFilter` that will add a cookie, or
* Add a parameter to the url.

The view will first look for the cookie and if not present for the parameter.

=== HttpServerFilter

Create a `HttpServerFilter` that will add a cookie with name `contextPath`.

.HttpServerFilter for context-path
[source,java]
----
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;

import org.reactivestreams.Publisher;

import io.micronaut.context.annotation.Requires;
import io.micronaut.context.annotation.Value;
import io.micronaut.core.async.publisher.Publishers;
import io.micronaut.http.HttpMethod;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.MutableHttpResponse;
import io.micronaut.http.annotation.Filter;
import io.micronaut.http.cookie.Cookie;
import io.micronaut.http.filter.HttpServerFilter;
import io.micronaut.http.filter.ServerFilterChain;

@Requires(property = "micronaut.server.context-path")
@Filter(methods = {HttpMethod.GET, HttpMethod.HEAD}, patterns = {"/**/rapidoc*", "/**/redoc*", "/**/swagger-ui*"})
public class OpenApiViewCookieContextPathFilter implements HttpServerFilter {
    private final Cookie contextPathCookie;

    OpenApiViewCookieContextPathFilter(@Value("${micronaut.server.context-path}") String contextPath) {
        this.contextPathCookie = Cookie.of("contextPath", URLEncoder.encode(contextPath, StandardCharsets.UTF_8) + ";max-age=2;samesite");
    }

    @Override
    public Publisher<MutableHttpResponse<?>> doFilter(HttpRequest<?> request, ServerFilterChain chain) {
        return Publishers.map(chain.proceed(request), response -> response.cookie(contextPathCookie));
    }

}
----

=== URL Parameter

Just add a parameter to the view url. For instance if the context path is set to `/context/path` you will access your view with `http://localhost:8080/context/path/swagger-ui?contextPath=%2Fcontext%2Fpath`.
