introduction: Introduction
releaseHistory: Release History
cli: Using the Micronaut CLI
gettingStarted: Dependencies
openApiDefinition: OpenAPI Definition
configuration:
  title: OpenAPI Processing Options
  propertiesFileConfiguration: Configuring OpenAPI Processing with a properties file
  systemPropertyConfiguration: Configuring OpenAPI Processing with system properties
  applicationConfiguration: Configuring OpenAPI Processing with an application.yml file
  availableOptions: Available OpenAPI processing options
exposingSwaggerOutput: Exposing Swagger Output
controllers: OpenAPI Generation for Controllers
namingStrategy: Naming Strategy
customSerializers: Custom serializers
schemaDecorators: Schema decorators
openApiGeneratorExtensions: OpenAPI Generator extensions
kotlin: Kotlin specific
swaggerAnnotations:
  title: Swagger Annotations
  schemasAndPojos: Schemas and POJOs
  schemasAndMetaAnnotations: Schemas and Meta Annotations
  schemasAndGenerics: Schemas and Generics
  schemasNaming: Schemas naming
  schemasAnnotationResolution: Schemas Annotation resolution
endpoints:
  title: Exposing Endpoints
  enableendpoints: Enable Endpoints
  endpointstags: Endpoints Tags
  micronautendpoints: Micronaut Built-In Endpoints
  endpointservers: Endpoints Servers
  endpointssecurityrequirements: Endpoints Security Requirements
  endpointspath: Endpoints Path
micronautOpenApiAnnotations:
  title: Micronaut OpenAPI annotations
  openapidecorator: '@OpenAPIDecorator'
  openapiextraschema: '@OpenAPIExtraSchema'
  openapigroup: '@OpenAPIGroup'
  openapigroupinfo: '@OpenAPIGroupInfo'
  openapiinclude: '@OpenAPIInclude'
  openapimanagement: '@OpenAPIManagement'
  openapisecurity: '@OpenAPISecurity'
  accessorsStyle: '@AccessorsStyle'
mergingSchemas: Merging Schemas
openApiViews:
  title: Generating OpenAPI Views
  mappingPath: Mapping Path
  viewsGenerationWithPropertiesFile: Enable Views Generation with a properties file
  viewsGenerationWithSystemProperties: Enable Views Generation with system properties
  swaggerui:
    title: Swagger-UI
    oauth2: Swagger UI - OAuth 2.0 configuration
  redoc: Redoc
  openapiExplorer: OpenAPI Explorer
  rapidoc: RapiDoc
  rapipdf: RapiPdf
convertToAdoc: Conversion to Asciidoc
versionsAndGroups:
  title: Versions and groups
  versions: Micronaut versioning
  groups: OpenAPI groups
serverContext:
  title: Server Context
  compileResolution: Compile Time Resolution
  serverFilter: HttpServerFilter
  urlParameter: URL Parameter
spring:
  title: Micronaut OpenAPI with Spring
  springWithGradle: Spring with Gradle
  springWithMaven: Spring with Maven
openApiGuides: Guides
repository: Repository
breaks: Breaking Changes
