Use a `HttpServerFilter` to add a cookie which contains the context-path. This can be done in two ways:

* Set the context-path from a static property (has to be set during compile time), or
* Parse the context path from the request headers. This is particularly useful if your application runs behind a reverse proxy, which strips the context-path before forwarding the request to the application. Most reverse proxies should provide the possibility to set the stripped context-path as a header (e.g. X-Forwarded-Prefix in the case of traefik).

=== Static Property

Create a `HttpServerFilter` that will add a cookie with name `contextPath`.

.HttpServerFilter for static context-path
snippet::io.micronaut.configuration.openapi.docs.filters.OpenApiViewCookieContextPathFilter[tags="imports,clazz", project-base="docs-examples/example", source="main"]

=== From HTTP Header

The `HttpServerFilter` looks very similar to the one above. The main difference is that it parses the `context-path` value from the request headers.

.HttpServerFilter from request headers
snippet::io.micronaut.configuration.openapi.docs.filters.OpenApiContextPathFilter[tags="imports,clazz", project-base="docs-examples/example", source="main"]
