spring:
  application:
    name: test-suite-kotlin-kapt-spring
  main:
    banner-mode: off

server:
  port: 8091

management:
  endpoints:
    web:
      path-mapping:
        health: /test
      base-path: /actuator2
      exposure:
        include: health,beans, metrics,info,prometheus,loggers, configprops, conditions
  server:
    base-path: /my
    port: 9091

logging:
  pattern:
    console: '%cyan(%d{HH:mm:ss.SSS}) %gray([%thread]) %highlight(%-5level) %magenta(%logger{36}) - %msg%n'
  level:
    root: info
