// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

// Protobuf Java Version: 3.25.2
package io.micronaut.openapi.proto;

public interface ProductsListProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.product.ProductsListProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.product.ProductProto products = 1;</code>
   */
  java.util.List<ProductProto>
      getProductsList();
  /**
   * <code>repeated .proto.product.ProductProto products = 1;</code>
   */
  ProductProto getProducts(int index);
  /**
   * <code>repeated .proto.product.ProductProto products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .proto.product.ProductProto products = 1;</code>
   */
  java.util.List<? extends ProductProtoOrBuilder>
      getProductsOrBuilderList();
  /**
   * <code>repeated .proto.product.ProductProto products = 1;</code>
   */
  ProductProtoOrBuilder getProductsOrBuilder(
      int index);
}
