// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

// Protobuf Java Version: 3.25.2
package io.micronaut.openapi.proto;

public interface ProductProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.product.ProductProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * this is comment
   * </pre>
   *
   * <code>int32 domain = 1;</code>
   * @return The domain.
   */
  int getDomain();

  /**
   * <pre>
   **
   *Unsigned int required field
   * </pre>
   *
   * <code>uint32 uintField = 2;</code>
   * @return The uintField.
   */
  int getUintField();

  /**
   * <code>optional int32 int32 = 3;</code>
   * @return Whether the int32 field is set.
   */
  boolean hasInt32();
  /**
   * <code>optional int32 int32 = 3;</code>
   * @return The int32.
   */
  int getInt32();

  /**
   * <code>optional int64 int64 = 4;</code>
   * @return Whether the int64 field is set.
   */
  boolean hasInt64();
  /**
   * <code>optional int64 int64 = 4;</code>
   * @return The int64.
   */
  long getInt64();

  /**
   * <code>optional uint32 uint32 = 5;</code>
   * @return Whether the uint32 field is set.
   */
  boolean hasUint32();
  /**
   * <code>optional uint32 uint32 = 5;</code>
   * @return The uint32.
   */
  int getUint32();

  /**
   * <code>optional uint64 uint64 = 6;</code>
   * @return Whether the uint64 field is set.
   */
  boolean hasUint64();
  /**
   * <code>optional uint64 uint64 = 6;</code>
   * @return The uint64.
   */
  long getUint64();

  /**
   * <code>optional bytes bytes = 7;</code>
   * @return Whether the bytes field is set.
   */
  boolean hasBytes();
  /**
   * <code>optional bytes bytes = 7;</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();

  /**
   * <code>optional double double = 8;</code>
   * @return Whether the double field is set.
   */
  boolean hasDouble();
  /**
   * <code>optional double double = 8;</code>
   * @return The double.
   */
  double getDouble();

  /**
   * <code>optional float float = 9;</code>
   * @return Whether the float field is set.
   */
  boolean hasFloat();
  /**
   * <code>optional float float = 9;</code>
   * @return The float.
   */
  float getFloat();

  /**
   * <code>optional bool bool = 10;</code>
   * @return Whether the bool field is set.
   */
  boolean hasBool();
  /**
   * <code>optional bool bool = 10;</code>
   * @return The bool.
   */
  boolean getBool();

  /**
   * <code>optional string string = 11;</code>
   * @return Whether the string field is set.
   */
  boolean hasString();
  /**
   * <code>optional string string = 11;</code>
   * @return The string.
   */
  String getString();
  /**
   * <code>optional string string = 11;</code>
   * @return The bytes for string.
   */
  com.google.protobuf.ByteString
      getStringBytes();

  /**
   * <code>optional fixed32 fixed32 = 12;</code>
   * @return Whether the fixed32 field is set.
   */
  boolean hasFixed32();
  /**
   * <code>optional fixed32 fixed32 = 12;</code>
   * @return The fixed32.
   */
  int getFixed32();

  /**
   * <code>optional fixed64 fixed64 = 13;</code>
   * @return Whether the fixed64 field is set.
   */
  boolean hasFixed64();
  /**
   * <code>optional fixed64 fixed64 = 13;</code>
   * @return The fixed64.
   */
  long getFixed64();

  /**
   * <code>optional sfixed32 sfixed32 = 14;</code>
   * @return Whether the sfixed32 field is set.
   */
  boolean hasSfixed32();
  /**
   * <code>optional sfixed32 sfixed32 = 14;</code>
   * @return The sfixed32.
   */
  int getSfixed32();

  /**
   * <code>optional sfixed64 sfixed64 = 15;</code>
   * @return Whether the sfixed64 field is set.
   */
  boolean hasSfixed64();
  /**
   * <code>optional sfixed64 sfixed64 = 15;</code>
   * @return The sfixed64.
   */
  long getSfixed64();

  /**
   * <code>optional sint32 sint32 = 16;</code>
   * @return Whether the sint32 field is set.
   */
  boolean hasSint32();
  /**
   * <code>optional sint32 sint32 = 16;</code>
   * @return The sint32.
   */
  int getSint32();

  /**
   * <code>optional sint64 sint64 = 17;</code>
   * @return Whether the sint64 field is set.
   */
  boolean hasSint64();
  /**
   * <code>optional sint64 sint64 = 17;</code>
   * @return The sint64.
   */
  long getSint64();

  /**
   * <code>.proto.product.MyEnum enumVal = 18;</code>
   * @return The enum numeric value on the wire for enumVal.
   */
  int getEnumValValue();
  /**
   * <code>.proto.product.MyEnum enumVal = 18;</code>
   * @return The enumVal.
   */
  MyEnum getEnumVal();

  /**
   * <code>map&lt;string, int32&gt; mapField = 19;</code>
   */
  int getMapFieldCount();
  /**
   * <code>map&lt;string, int32&gt; mapField = 19;</code>
   */
  boolean containsMapField(
      String key);
  /**
   * Use {@link #getMapFieldMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Integer>
  getMapField();
  /**
   * <code>map&lt;string, int32&gt; mapField = 19;</code>
   */
  java.util.Map<String, Integer>
  getMapFieldMap();
  /**
   * <code>map&lt;string, int32&gt; mapField = 19;</code>
   */
  int getMapFieldOrDefault(
      String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; mapField = 19;</code>
   */
  int getMapFieldOrThrow(
      String key);

  /**
   * <code>.google.protobuf.Any anyValue = 200;</code>
   * @return Whether the anyValue field is set.
   */
  boolean hasAnyValue();
  /**
   * <code>.google.protobuf.Any anyValue = 200;</code>
   * @return The anyValue.
   */
  com.google.protobuf.Any getAnyValue();
  /**
   * <code>.google.protobuf.Any anyValue = 200;</code>
   */
  com.google.protobuf.AnyOrBuilder getAnyValueOrBuilder();

  /**
   * <code>.google.protobuf.Api apiValue = 201;</code>
   * @return Whether the apiValue field is set.
   */
  boolean hasApiValue();
  /**
   * <code>.google.protobuf.Api apiValue = 201;</code>
   * @return The apiValue.
   */
  com.google.protobuf.Api getApiValue();
  /**
   * <code>.google.protobuf.Api apiValue = 201;</code>
   */
  com.google.protobuf.ApiOrBuilder getApiValueOrBuilder();

  /**
   * <code>.google.protobuf.Duration durationValue = 202;</code>
   * @return Whether the durationValue field is set.
   */
  boolean hasDurationValue();
  /**
   * <code>.google.protobuf.Duration durationValue = 202;</code>
   * @return The durationValue.
   */
  com.google.protobuf.Duration getDurationValue();
  /**
   * <code>.google.protobuf.Duration durationValue = 202;</code>
   */
  com.google.protobuf.DurationOrBuilder getDurationValueOrBuilder();

  /**
   * <code>.google.protobuf.Empty emptyValue = 203;</code>
   * @return Whether the emptyValue field is set.
   */
  boolean hasEmptyValue();
  /**
   * <code>.google.protobuf.Empty emptyValue = 203;</code>
   * @return The emptyValue.
   */
  com.google.protobuf.Empty getEmptyValue();
  /**
   * <code>.google.protobuf.Empty emptyValue = 203;</code>
   */
  com.google.protobuf.EmptyOrBuilder getEmptyValueOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp timestampValue = 204;</code>
   * @return Whether the timestampValue field is set.
   */
  boolean hasTimestampValue();
  /**
   * <code>.google.protobuf.Timestamp timestampValue = 204;</code>
   * @return The timestampValue.
   */
  com.google.protobuf.Timestamp getTimestampValue();
  /**
   * <code>.google.protobuf.Timestamp timestampValue = 204;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampValueOrBuilder();

  /**
   * <code>.google.protobuf.Struct structValue = 205;</code>
   * @return Whether the structValue field is set.
   */
  boolean hasStructValue();
  /**
   * <code>.google.protobuf.Struct structValue = 205;</code>
   * @return The structValue.
   */
  com.google.protobuf.Struct getStructValue();
  /**
   * <code>.google.protobuf.Struct structValue = 205;</code>
   */
  com.google.protobuf.StructOrBuilder getStructValueOrBuilder();

  /**
   * <pre>
   * wrapper types
   * </pre>
   *
   * <code>optional .google.protobuf.Int32Value int32Val = 301;</code>
   * @return Whether the int32Val field is set.
   */
  boolean hasInt32Val();
  /**
   * <pre>
   * wrapper types
   * </pre>
   *
   * <code>optional .google.protobuf.Int32Value int32Val = 301;</code>
   * @return The int32Val.
   */
  com.google.protobuf.Int32Value getInt32Val();
  /**
   * <pre>
   * wrapper types
   * </pre>
   *
   * <code>optional .google.protobuf.Int32Value int32Val = 301;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getInt32ValOrBuilder();

  /**
   * <code>optional .google.protobuf.Int64Value int64Val = 302;</code>
   * @return Whether the int64Val field is set.
   */
  boolean hasInt64Val();
  /**
   * <code>optional .google.protobuf.Int64Value int64Val = 302;</code>
   * @return The int64Val.
   */
  com.google.protobuf.Int64Value getInt64Val();
  /**
   * <code>optional .google.protobuf.Int64Value int64Val = 302;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getInt64ValOrBuilder();

  /**
   * <code>optional .google.protobuf.UInt32Value uint32Val = 303;</code>
   * @return Whether the uint32Val field is set.
   */
  boolean hasUint32Val();
  /**
   * <code>optional .google.protobuf.UInt32Value uint32Val = 303;</code>
   * @return The uint32Val.
   */
  com.google.protobuf.UInt32Value getUint32Val();
  /**
   * <code>optional .google.protobuf.UInt32Value uint32Val = 303;</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getUint32ValOrBuilder();

  /**
   * <code>optional .google.protobuf.UInt64Value uint64Val = 304;</code>
   * @return Whether the uint64Val field is set.
   */
  boolean hasUint64Val();
  /**
   * <code>optional .google.protobuf.UInt64Value uint64Val = 304;</code>
   * @return The uint64Val.
   */
  com.google.protobuf.UInt64Value getUint64Val();
  /**
   * <code>optional .google.protobuf.UInt64Value uint64Val = 304;</code>
   */
  com.google.protobuf.UInt64ValueOrBuilder getUint64ValOrBuilder();

  /**
   * <code>optional .google.protobuf.BytesValue bytesVal = 305;</code>
   * @return Whether the bytesVal field is set.
   */
  boolean hasBytesVal();
  /**
   * <code>optional .google.protobuf.BytesValue bytesVal = 305;</code>
   * @return The bytesVal.
   */
  com.google.protobuf.BytesValue getBytesVal();
  /**
   * <code>optional .google.protobuf.BytesValue bytesVal = 305;</code>
   */
  com.google.protobuf.BytesValueOrBuilder getBytesValOrBuilder();

  /**
   * <code>optional .google.protobuf.DoubleValue doubleVal = 306;</code>
   * @return Whether the doubleVal field is set.
   */
  boolean hasDoubleVal();
  /**
   * <code>optional .google.protobuf.DoubleValue doubleVal = 306;</code>
   * @return The doubleVal.
   */
  com.google.protobuf.DoubleValue getDoubleVal();
  /**
   * <code>optional .google.protobuf.DoubleValue doubleVal = 306;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getDoubleValOrBuilder();

  /**
   * <code>optional .google.protobuf.FloatValue floatVal = 307;</code>
   * @return Whether the floatVal field is set.
   */
  boolean hasFloatVal();
  /**
   * <code>optional .google.protobuf.FloatValue floatVal = 307;</code>
   * @return The floatVal.
   */
  com.google.protobuf.FloatValue getFloatVal();
  /**
   * <code>optional .google.protobuf.FloatValue floatVal = 307;</code>
   */
  com.google.protobuf.FloatValueOrBuilder getFloatValOrBuilder();

  /**
   * <code>optional .google.protobuf.BoolValue boolVal = 308;</code>
   * @return Whether the boolVal field is set.
   */
  boolean hasBoolVal();
  /**
   * <code>optional .google.protobuf.BoolValue boolVal = 308;</code>
   * @return The boolVal.
   */
  com.google.protobuf.BoolValue getBoolVal();
  /**
   * <code>optional .google.protobuf.BoolValue boolVal = 308;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getBoolValOrBuilder();

  /**
   * <code>optional .google.protobuf.StringValue stringVal = 309;</code>
   * @return Whether the stringVal field is set.
   */
  boolean hasStringVal();
  /**
   * <code>optional .google.protobuf.StringValue stringVal = 309;</code>
   * @return The stringVal.
   */
  com.google.protobuf.StringValue getStringVal();
  /**
   * <code>optional .google.protobuf.StringValue stringVal = 309;</code>
   */
  com.google.protobuf.StringValueOrBuilder getStringValOrBuilder();

  /**
   * <code>optional .proto.product.SubObjectProto subObject = 1000;</code>
   * @return Whether the subObject field is set.
   */
  boolean hasSubObject();
  /**
   * <code>optional .proto.product.SubObjectProto subObject = 1000;</code>
   * @return The subObject.
   */
  SubObjectProto getSubObject();
  /**
   * <code>optional .proto.product.SubObjectProto subObject = 1000;</code>
   */
  SubObjectProtoOrBuilder getSubObjectOrBuilder();
}
