// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

// Protobuf Java Version: 3.25.2
package io.micronaut.openapi.proto;

public final class ProductsProtos {
  private ProductsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_product_ProductsListProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_product_ProductsListProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_product_ProductProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_product_ProductProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_product_ProductProto_MapFieldEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_product_ProductProto_MapFieldEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_product_SubObjectProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_product_SubObjectProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016products.proto\022\rproto.product\032\031google/" +
      "protobuf/any.proto\032\031google/protobuf/api." +
      "proto\032\036google/protobuf/duration.proto\032\033g" +
      "oogle/protobuf/empty.proto\032\034google/proto" +
      "buf/struct.proto\032\037google/protobuf/timest" +
      "amp.proto\032\036google/protobuf/wrappers.prot" +
      "o\"B\n\021ProductsListProto\022-\n\010products\030\001 \003(\013" +
      "2\033.proto.product.ProductProto\"\350\014\n\014Produc" +
      "tProto\022\016\n\006domain\030\001 \001(\005\022\021\n\tuintField\030\002 \001(" +
      "\r\022\022\n\005int32\030\003 \001(\005H\000\210\001\001\022\022\n\005int64\030\004 \001(\003H\001\210\001" +
      "\001\022\023\n\006uint32\030\005 \001(\rH\002\210\001\001\022\023\n\006uint64\030\006 \001(\004H\003" +
      "\210\001\001\022\022\n\005bytes\030\007 \001(\014H\004\210\001\001\022\023\n\006double\030\010 \001(\001H" +
      "\005\210\001\001\022\022\n\005float\030\t \001(\002H\006\210\001\001\022\021\n\004bool\030\n \001(\010H\007" +
      "\210\001\001\022\023\n\006string\030\013 \001(\tH\010\210\001\001\022\024\n\007fixed32\030\014 \001(" +
      "\007H\t\210\001\001\022\024\n\007fixed64\030\r \001(\006H\n\210\001\001\022\025\n\010sfixed32" +
      "\030\016 \001(\017H\013\210\001\001\022\025\n\010sfixed64\030\017 \001(\020H\014\210\001\001\022\023\n\006si" +
      "nt32\030\020 \001(\021H\r\210\001\001\022\023\n\006sint64\030\021 \001(\022H\016\210\001\001\022&\n\007" +
      "enumVal\030\022 \001(\0162\025.proto.product.MyEnum\022;\n\010" +
      "mapField\030\023 \003(\0132).proto.product.ProductPr" +
      "oto.MapFieldEntry\022\'\n\010anyValue\030\310\001 \001(\0132\024.g" +
      "oogle.protobuf.Any\022\'\n\010apiValue\030\311\001 \001(\0132\024." +
      "google.protobuf.Api\0221\n\rdurationValue\030\312\001 " +
      "\001(\0132\031.google.protobuf.Duration\022+\n\nemptyV" +
      "alue\030\313\001 \001(\0132\026.google.protobuf.Empty\0223\n\016t" +
      "imestampValue\030\314\001 \001(\0132\032.google.protobuf.T" +
      "imestamp\022-\n\013structValue\030\315\001 \001(\0132\027.google." +
      "protobuf.Struct\0223\n\010int32Val\030\255\002 \001(\0132\033.goo" +
      "gle.protobuf.Int32ValueH\017\210\001\001\0223\n\010int64Val" +
      "\030\256\002 \001(\0132\033.google.protobuf.Int64ValueH\020\210\001" +
      "\001\0225\n\tuint32Val\030\257\002 \001(\0132\034.google.protobuf." +
      "UInt32ValueH\021\210\001\001\0225\n\tuint64Val\030\260\002 \001(\0132\034.g" +
      "oogle.protobuf.UInt64ValueH\022\210\001\001\0223\n\010bytes" +
      "Val\030\261\002 \001(\0132\033.google.protobuf.BytesValueH" +
      "\023\210\001\001\0225\n\tdoubleVal\030\262\002 \001(\0132\034.google.protob" +
      "uf.DoubleValueH\024\210\001\001\0223\n\010floatVal\030\263\002 \001(\0132\033" +
      ".google.protobuf.FloatValueH\025\210\001\001\0221\n\007bool" +
      "Val\030\264\002 \001(\0132\032.google.protobuf.BoolValueH\026" +
      "\210\001\001\0225\n\tstringVal\030\265\002 \001(\0132\034.google.protobu" +
      "f.StringValueH\027\210\001\001\0226\n\tsubObject\030\350\007 \001(\0132\035" +
      ".proto.product.SubObjectProtoH\030\210\001\001\032/\n\rMa" +
      "pFieldEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:" +
      "\0028\001B\010\n\006_int32B\010\n\006_int64B\t\n\007_uint32B\t\n\007_u" +
      "int64B\010\n\006_bytesB\t\n\007_doubleB\010\n\006_floatB\007\n\005" +
      "_boolB\t\n\007_stringB\n\n\010_fixed32B\n\n\010_fixed64" +
      "B\013\n\t_sfixed32B\013\n\t_sfixed64B\t\n\007_sint32B\t\n" +
      "\007_sint64B\013\n\t_int32ValB\013\n\t_int64ValB\014\n\n_u" +
      "int32ValB\014\n\n_uint64ValB\013\n\t_bytesValB\014\n\n_" +
      "doubleValB\013\n\t_floatValB\n\n\010_boolValB\014\n\n_s" +
      "tringValB\014\n\n_subObjectR\003fooR\003bar\"\"\n\016SubO" +
      "bjectProto\022\020\n\010reqField\030\001 \001(\005*&\n\006MyEnum\022\r" +
      "\n\tENUM_VAL1\020\000\022\r\n\tENUM_VAL2\020\001B.\n\032io.micro" +
      "naut.openapi.protoB\016ProductsProtosP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.ApiProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_proto_product_ProductsListProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_product_ProductsListProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_product_ProductsListProto_descriptor,
        new String[] { "Products", });
    internal_static_proto_product_ProductProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_product_ProductProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_product_ProductProto_descriptor,
        new String[] { "Domain", "UintField", "Int32", "Int64", "Uint32", "Uint64", "Bytes", "Double", "Float", "Bool", "String", "Fixed32", "Fixed64", "Sfixed32", "Sfixed64", "Sint32", "Sint64", "EnumVal", "MapField", "AnyValue", "ApiValue", "DurationValue", "EmptyValue", "TimestampValue", "StructValue", "Int32Val", "Int64Val", "Uint32Val", "Uint64Val", "BytesVal", "DoubleVal", "FloatVal", "BoolVal", "StringVal", "SubObject", });
    internal_static_proto_product_ProductProto_MapFieldEntry_descriptor =
      internal_static_proto_product_ProductProto_descriptor.getNestedTypes().get(0);
    internal_static_proto_product_ProductProto_MapFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_product_ProductProto_MapFieldEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_proto_product_SubObjectProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_product_SubObjectProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_product_SubObjectProto_descriptor,
        new String[] { "ReqField", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.ApiProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
