// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

// Protobuf Java Version: 3.25.2
package io.micronaut.openapi.proto;

public interface SubObjectProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.product.SubObjectProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 reqField = 1;</code>
   * @return The reqField.
   */
  int getReqField();
}
