micronaut.openapi.expand.api.version=v1.1
micronaut.openapi.expand.openapi.description=A nice API

micronaut.openapi.tag.generation.by.class.enabled=true
micronaut.openapi.tag.generation.remove.prefixes=
micronaut.openapi.tag.generation.remove.postfixes=Api, Controller
micronaut.openapi.tag.generation.naming.strategy=KEBAB_CASE
